// <auto-generated />
using System;
using HepsiApi.Persistence.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HepsiApi.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251119114548_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CategoryProduct", b =>
                {
                    b.Property<int>("Categoriesid")
                        .HasColumnType("int");

                    b.Property<int>("Productsid")
                        .HasColumnType("int");

                    b.HasKey("Categoriesid", "Productsid");

                    b.HasIndex("Productsid");

                    b.ToTable("CategoryProduct");
                });

            modelBuilder.Entity("HepsiApi.Domain.Entities.Brand", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("createdDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("isDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("id");

                    b.ToTable("Brands");

                    b.HasData(
                        new
                        {
                            id = 1,
                            createdDate = new DateTime(2025, 11, 19, 14, 45, 48, 409, DateTimeKind.Local).AddTicks(3738),
                            isDeleted = false,
                            name = "Clothing, Home & Kids"
                        },
                        new
                        {
                            id = 2,
                            createdDate = new DateTime(2025, 11, 19, 14, 45, 48, 409, DateTimeKind.Local).AddTicks(3762),
                            isDeleted = false,
                            name = "Games, Health & Automotive"
                        },
                        new
                        {
                            id = 3,
                            createdDate = new DateTime(2025, 11, 19, 14, 45, 48, 409, DateTimeKind.Local).AddTicks(3772),
                            isDeleted = true,
                            name = "Outdoors"
                        });
                });

            modelBuilder.Entity("HepsiApi.Domain.Entities.Category", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("createdDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("isDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("parentId")
                        .HasColumnType("int");

                    b.Property<int>("priorty")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            id = 1,
                            createdDate = new DateTime(2025, 11, 19, 14, 45, 48, 409, DateTimeKind.Local).AddTicks(5001),
                            isDeleted = false,
                            name = "Elektronik",
                            parentId = 0,
                            priorty = 1
                        },
                        new
                        {
                            id = 2,
                            createdDate = new DateTime(2025, 11, 19, 14, 45, 48, 409, DateTimeKind.Local).AddTicks(5003),
                            isDeleted = false,
                            name = "Moda",
                            parentId = 0,
                            priorty = 2
                        },
                        new
                        {
                            id = 3,
                            createdDate = new DateTime(2025, 11, 19, 14, 45, 48, 409, DateTimeKind.Local).AddTicks(5005),
                            isDeleted = false,
                            name = "Bilgisayar",
                            parentId = 1,
                            priorty = 1
                        },
                        new
                        {
                            id = 4,
                            createdDate = new DateTime(2025, 11, 19, 14, 45, 48, 409, DateTimeKind.Local).AddTicks(5006),
                            isDeleted = false,
                            name = "Kadin",
                            parentId = 2,
                            priorty = 1
                        });
                });

            modelBuilder.Entity("HepsiApi.Domain.Entities.Detail", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("categoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("createdDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("categoryId");

                    b.ToTable("Details");

                    b.HasData(
                        new
                        {
                            id = 1,
                            categoryId = 1,
                            createdDate = new DateTime(2025, 11, 19, 14, 45, 48, 410, DateTimeKind.Local).AddTicks(8498),
                            description = "Qui sayfası iure iusto çıktılar.",
                            isDeleted = false,
                            title = "Cezbelendi."
                        },
                        new
                        {
                            id = 2,
                            categoryId = 3,
                            createdDate = new DateTime(2025, 11, 19, 14, 45, 48, 410, DateTimeKind.Local).AddTicks(8535),
                            description = "Eum şafak salladı qui gidecekmiş.",
                            isDeleted = true,
                            title = "Architecto incidunt."
                        },
                        new
                        {
                            id = 3,
                            categoryId = 4,
                            createdDate = new DateTime(2025, 11, 19, 14, 45, 48, 410, DateTimeKind.Local).AddTicks(8564),
                            description = "Odio bahar qui ab aut.",
                            isDeleted = false,
                            title = "Teldeki."
                        });
                });

            modelBuilder.Entity("HepsiApi.Domain.Entities.Product", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("brandId")
                        .HasColumnType("int");

                    b.Property<DateTime>("createdDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("discount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("isDeleted")
                        .HasColumnType("bit");

                    b.Property<decimal>("price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("brandId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            id = 1,
                            brandId = 1,
                            createdDate = new DateTime(2025, 11, 19, 14, 45, 48, 412, DateTimeKind.Local).AddTicks(1300),
                            description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            discount = 6.904042489890240m,
                            isDeleted = false,
                            price = 990.70m,
                            title = "Incredible Frozen Pizza"
                        },
                        new
                        {
                            id = 2,
                            brandId = 3,
                            createdDate = new DateTime(2025, 11, 19, 14, 45, 48, 412, DateTimeKind.Local).AddTicks(1330),
                            description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            discount = 0.5973208547271870m,
                            isDeleted = false,
                            price = 319.66m,
                            title = "Awesome Steel Shoes"
                        });
                });

            modelBuilder.Entity("CategoryProduct", b =>
                {
                    b.HasOne("HepsiApi.Domain.Entities.Category", null)
                        .WithMany()
                        .HasForeignKey("Categoriesid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HepsiApi.Domain.Entities.Product", null)
                        .WithMany()
                        .HasForeignKey("Productsid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HepsiApi.Domain.Entities.Detail", b =>
                {
                    b.HasOne("HepsiApi.Domain.Entities.Category", "Category")
                        .WithMany("Details")
                        .HasForeignKey("categoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("HepsiApi.Domain.Entities.Product", b =>
                {
                    b.HasOne("HepsiApi.Domain.Entities.Brand", "Brand")
                        .WithMany()
                        .HasForeignKey("brandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");
                });

            modelBuilder.Entity("HepsiApi.Domain.Entities.Category", b =>
                {
                    b.Navigation("Details");
                });
#pragma warning restore 612, 618
        }
    }
}
